server:
  undertow:
    io-threads: 4
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /upload
  port: 8087
spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

#Ip白名单
whiteList: @white.list@
