server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /upload
  port: 8087
spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

